import localFont from "next/font/local";
import "./globals.css";
// import HeaderPage from "./_components/Header";
import FooterPage from "./_components/Footer";
import { Providers } from "./_components/redux/providers";
import HeaderTest from "./_components/HeaderTest";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* <HeaderTest /> */}
        {/* <HeaderPage /> */}
        {children}
        <FooterPage />
        </Providers>
      </body>
    </html>
  );
}
