import localFont from "next/font/local";
import { Roboto } from 'next/font/google';
import "./globals.css";
import HeaderPage from "./_components/Header";
import FooterPage from "./_components/Footer";
import { Providers } from "./_components/redux/providers";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify the font weights you need
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
     
     <Providers>
          {/* <HeaderTest /> */}
        <HeaderPage />
        {children}
        <FooterPage />
        </Providers>
        
      
      </body>
    </html>
  );
}
